import { en, type Strings } from './en';

/**
 * th — generated by `scripts/i18n-scaffold.mjs` from en.ts and the DeepL
 * cache (#22), then REVIEWED BY HAND. Re-rendering discards those reviews, so
 * the generator refuses to overwrite this file without `--force`.
 *
 * 51 keys are the English original, referenced as `en.<key>` rather
 * than copied: every parameterised message in this catalogue is an arrow
 * function, and a translator returns prose, not a function body. They are
 * visible here, greppable, and pinned as an exact set by
 * tests/unit/locale-fallbacks.test.ts — so one cannot be added quietly, and
 * one that gets translated must be removed from that list to stay green.
 *
 * MACHINE-TRANSLATED COPY IS A FIRST DRAFT. It has been checked for structure
 * — placeholders intact, protected names preserved, nothing empty — and NOT
 * for fluency, which needs a speaker of this language.
 */
export const th: Strings = {
  title: 'เครื่องมือสร้างกลุ่มในห้องเรียน',
  description:
    'แบ่งชั้นเรียนเป็นกลุ่มได้ทันที — ในเบราว์เซอร์ของคุณ โดยไม่ต้องส่งข้อมูลไปที่ใดทั้งสิ้น',
  heading: 'เครื่องมือสร้างกลุ่มในห้องเรียน',
  lead: 'บอกระบบว่าชั้นเรียนของคุณมีนักเรียนกี่คน และต้องการให้นักเรียนในกลุ่มละกี่คน ระบบจะสับเปลี่ยนและจัดนักเรียนให้แต่ละกลุ่ม โดยไม่มีกลุ่มใดที่มีจำนวนนักเรียนน้อยกว่าที่คุณกำหนด',
  privacy:
    'ทุกอย่างเกิดขึ้นในเบราว์เซอร์ของคุณเท่านั้น รายชื่อชั้นเรียนจะไม่ถูกส่งออกจากหน้านี้เลย',
  howToHeading: 'วิธีใช้',
  howToWhat:
    'ออกแบบมาสำหรับครู โดยShyden การแบ่งชั้นเรียนให้ยุติธรรมนั้นใช้เวลามาก ซึ่งคุณอาจไม่มีเวลาพอ และการทำด้วยมืออาจก่อให้เกิดข้อโต้แย้งว่าครูมีนักเรียนคนโปรด การแบ่งชั้นเรียนนี้ทำได้เพียงคลิกเดียว — ฟรี ไม่ต้องสมัคร และข้อมูลเกี่ยวกับชั้นเรียนของคุณจะไม่ถูกส่งออกจากเบราว์เซอร์เลย',
  howToSteps: [
    'บอกจำนวนนักเรียนในชั้นของคุณว่ามีกี่คน',
    'เลือกวิธีแบ่งพวกมัน',
    'กด "สร้างกลุ่ม"',
  ],
  classLabel: 'คลาส (ไม่บังคับ)',
  studentsLabel: 'จำนวนนักเรียน',
  studentsHelp:
    'นักเรียนจะไม่เปิดเผยชื่อและถูกกำหนดด้วยหมายเลข — นักเรียน 1, นักเรียน 2, และต่อไปเรื่อยๆ',
  studentsLockedReason:
    'กำหนดตามรายชื่อของคุณ เพิ่มหรือลบนักเรียนในส่วน "รายละเอียดนักเรียน" เพื่อปรับเปลี่ยน',
  modeLabel: 'แบ่งตาม',
  modePerGroup: 'จำนวนนักเรียนต่อกลุ่ม',
  modeGroupCount: 'จำนวนกลุ่ม',
  groupSizeLabel: 'นักเรียนในแต่ละกลุ่ม',
  groupCountLabel: 'มีกี่กลุ่ม',
  sexMixLabel: 'แบ่งเด็กชายและเด็กหญิงให้เท่ากัน',
  sexSeparateLabel: 'ให้เด็กชายและเด็กหญิงอยู่แยกกัน',
  sexWhyNoList:
    'เพิ่มชื่อนักเรียนของคุณในส่วน "รายละเอียดนักเรียน" และกำหนดเพศ (M หรือ F) สำหรับแต่ละคนเพื่อใช้ฟังก์ชันนี้',
  sexWhyUnset: en.sexWhyUnset,
  sexWhyReturning: en.sexWhyReturning,
  leftoversLabel: 'หากมีนักเรียนเหลือ',
  leftoversSpread: 'แบ่งให้เท่ากัน',
  leftoversBunch: 'รวมทั้งหมดไว้ในกลุ่มเดียว',
  leftoversHelp: 'ไม่ว่าจะอย่างไร กลุ่มใดก็ตามจะไม่เล็กกว่าขนาดที่คุณเลือกไว้',
  soundOn: 'เปิดเสียง',
  soundOff: 'แสดงความคิดเห็น',
  speedLabel: 'ความเร็ว',
  speedNormal: 'ปกติ',
  speedFast: 'เร็ว',
  speedSkip: 'ข้ามส่วนแอนิเมชัน',
  sectionStudentsHeading: 'ข้อมูลนักเรียน',
  sectionGroupingHeading: 'ตัวเลือกการจัดกลุ่ม',
  sectionImportExportHeading: 'นำเข้า / ส่งออก',
  sectionSoundHeading: 'เสียงและภาพเคลื่อนไหว',
  rosterColNumber: '#',
  rosterColName: 'ชื่อ',
  rosterColSex: 'เพศ',
  rosterColAbsent: 'ไม่มา',
  rosterColTogether: 'ร่วมกัน',
  rosterColApart: 'แยก',
  rosterUnset: '—',
  rosterSexMale: 'M',
  rosterSexFemale: 'F',
  rosterAddStudent: '+ เพิ่มนักเรียน',
  rosterAddSeveral: '+ เพิ่มอีกหลาย…',
  rosterHowMany: 'เพิ่มกี่ชิ้น?',
  rosterAddConfirm: 'เพิ่ม',
  rosterAbsentPill: 'ไม่มา',
  rosterAbsentConsequence:
    'นักเรียนที่ถูกบันทึกว่าขาดเรียนจะไม่ถูกนับรวมในการจัดกลุ่ม',
  rosterCountLine: en.rosterCountLine,
  rosterDuplicateMessage: en.rosterDuplicateMessage,
  rosterNoSexMessage: en.rosterNoSexMessage,
  rosterClashMessage: en.rosterClashMessage,
  rosterGapWarning: en.rosterGapWarning,
  rosterOpenRefusedMessage: en.rosterOpenRefusedMessage,
  rosterAtLimitMessage: en.rosterAtLimitMessage,
  rosterRoomMessage: en.rosterRoomMessage,
  rosterRemove: 'ลบ',
  rosterClearAll: 'ลบทั้งหมด',
  stateNoneAdded: 'ยังไม่มีข้อมูล',
  stateNamed: en.stateNamed,
  stateAbsent: en.stateAbsent,
  stateTogether: en.stateTogether,
  stateApart: en.stateApart,
  stateAdded: en.stateAdded,
  stateNone: 'ไม่มี',
  stateMixed: 'แบ่งตามเพศ',
  stateSeparated: 'แบ่งตามเพศ',
  stateBunched: 'อาหารเหลือในกลุ่มหนึ่ง',
  stateNothingToSave: 'ยังไม่มีอะไรที่จะบันทึก',
  stateUnsaved:
    'การเปลี่ยนแปลงที่ยังไม่บันทึก — ส่งออกเพื่อเก็บรักษาการเปลี่ยนแปลงเหล่านั้น',
  makeGroups: 'สร้างกลุ่ม',
  again: 'สับไพ่ใหม่',
  needsJs: 'เครื่องมือนี้ต้องเปิดใช้งาน JavaScript',
  resultsHeading: 'กลุ่มของคุณ',
  resultsHeadingNamed: en.resultsHeadingNamed,
  resultsSummary: en.resultsSummary,
  groupLabel: en.groupLabel,
  studentNumber: en.studentNumber,
  staleMode: 'กลุ่มเหล่านี้ไม่ทันสมัยแล้ว — ขนาดของกลุ่มได้เปลี่ยนแปลงไปแล้ว',
  staleLeftovers:
    'กลุ่มเหล่านี้ล้าสมัยแล้ว — ตัวเลือกของ "เหลือ" ได้เปลี่ยนไปแล้ว',
  staleSexMode:
    'กลุ่มเหล่านี้ล้าสมัยแล้ว — วิธีแบ่งกลุ่มเด็กชายและเด็กหญิงได้เปลี่ยนแปลงไปแล้ว',
  staleRoster: 'กลุ่มเหล่านี้ล้าสมัยแล้ว — รายชื่อชั้นเรียนได้เปลี่ยนแปลงแล้ว',
  csvProblemEmptyFile: 'ไฟล์นี้ว่างเปล่า',
  csvProblemUnreadable: 'ไม่สามารถอ่านไฟล์นั้นได้ โปรดลองเลือกไฟล์นั้นอีกครั้ง',
  csvProblemNoNumberColumn:
    'ไฟล์นี้ไม่มีคอลัมน์หมายเลข นักเรียนทุกคนจำเป็นต้องมีหนึ่งคอลัมน์',
  csvProblemNumberBlank: en.csvProblemNumberBlank,
  csvProblemNumberNotWhole: en.csvProblemNumberNotWhole,
  csvProblemDuplicateNumber: en.csvProblemDuplicateNumber,
  csvProblemSex: en.csvProblemSex,
  csvProblemAbsent: en.csvProblemAbsent,
  csvProblemLetter: en.csvProblemLetter,
  csvProblemTooMany: en.csvProblemTooMany,
  csvWrongLanguage: en.csvWrongLanguage,
  csvLanguageName: {
    en: 'ภาษาอังกฤษ',
    id: 'ภาษาอินโดนีเซีย',
    zh: 'ภาษาจีน',
    vi: 'ภาษาเวียดนาม',
    th: 'ไทย',
  },
  csvLanguageVersion: {
    en: 'ภาษาอังกฤษ',
    id: 'ภาษาอินโดนีเซีย',
    zh: 'ภาษาจีน',
    vi: 'ภาษาเวียดนาม',
    th: 'ไทย',
  },
  ioExportClassList: 'ส่งออกรายชื่อชั้นเรียน',
  ioExportGroups: 'กลุ่มการส่งออก',
  ioDownloadTemplate: 'ดาวน์โหลดแม่แบบ',
  ioImportLabel: 'นำเข้ารายชื่อชั้นเรียน',
  ioProblemsHeading: 'ไฟล์นี้ยังไม่ถูกนำเข้า:',
  ioReplaceWarning: en.ioReplaceWarning,
  ioReplaceConfirm: 'เปลี่ยนมัน',
  ioReplaceCancel: 'เก็บสิ่งที่ฉันมีไว้',
  ioImported: en.ioImported,
  ioBothLanguages: 'ส่งออกเป็นภาษาอื่นด้วย',
  ioBothLanguagesHint:
    'ไฟล์ของคุณถูกบันทึกแล้ว ในภาษานี้ แท็บที่สองจะเปิดขึ้นในภาษาที่คุณเลือก พร้อมด้วยรายชื่อชั้นเรียนเดียวกัน เพื่อให้คุณตรวจสอบและบันทึกที่นั่น ไม่มีข้อมูลใดถูกเก็บไว้ และไม่มีข้อมูลใดถูกส่งไปที่ใดทั้งสิ้น',
  ioHandoverBlocked:
    'ไม่สามารถเปิดแท็บที่สองได้ รายชื่อชั้นเรียนของคุณยังอยู่ที่นี่ — โปรดอนุญาตหน้าต่างป๊อปอัพแล้วลองอีกครั้ง',
  ioHandoverTimedOut:
    'แท็บที่สองไม่เคยขอรายชื่อชั้นเรียนเลย รายชื่อชั้นเรียนของคุณยังอยู่ที่นี่ — ปิดแท็บนั้นแล้วลองอีกครั้ง',
  ioHandoverNotOffered:
    'ยังไม่ได้รับรายชื่อนักเรียน โปรดกลับไปยังแท็บอื่นและลองอีกครั้ง',
  ioHandoverSent: en.ioHandoverSent,
  printOpen: 'พิมพ์',
  printHeading: 'พิมพ์',
  printWhat: 'พิมพ์อะไร',
  printWhatClassList: 'รายชื่อนักเรียน',
  printWhatGroups: 'ผลประกอบการของกลุ่ม',
  printWhatBoth: 'ทั้งสอง',
  printOnTheClassList: 'ในรายชื่อนักเรียน',
  printShowAbsent: 'แสดงรายชื่อนักเรียนที่ขาดเรียน',
  printShowLetters:
    'แสดงตัวอักษรที่เกี่ยวข้องกับเพศ และตัวอักษรที่รวมกัน/แยกกัน',
  printIncludeAvatars: 'เพิ่มรูปโปรไฟล์',
  printCancel: 'ยกเลิก',
  printConfirm: 'พิมพ์',
  printClassListHeading: 'รายชื่อนักเรียน',
  printGroupsHeading: 'กลุ่ม',
  printedOn: en.printedOn,
  printHereToday: en.printHereToday,
  boardOpen: 'หน้าจอเต็ม',
  boardExit: 'ปิดโหมดเต็มหน้าจอ',
  boardShuffle: 'สับไพ่ใหม่',
  staleRefuseExport: 'กลุ่มเหล่านี้ล้าสมัยแล้ว โปรดจัดเรียงใหม่ก่อนที่จะบันทึก',
  staleRefusePrint: 'กลุ่มเหล่านี้ล้าสมัยแล้ว โปรดจัดเรียงใหม่ก่อนพิมพ์',
  staleRefuseBoard: 'กลุ่มเหล่านี้ล้าสมัยแล้ว โปรดสับใหม่ก่อนที่จะแสดงออกมา',
  errors: {
    NO_STUDENTS:
      'เพิ่มนักเรียนบ้าง หรือตรวจสอบให้แน่ใจว่าอย่างน้อยมีนักเรียนหนึ่งคนที่ไม่ถูกบันทึกว่าขาดเรียน',
    TOO_MANY_STUDENTS: en.errors.TOO_MANY_STUDENTS,
    DUPLICATE_NUMBER: en.errors.DUPLICATE_NUMBER,
    INVALID_GROUP_SIZE: 'แต่ละกลุ่มต้องมีนักเรียนอย่างน้อย 1 คน',
    INVALID_GROUP_COUNT: 'คุณต้องมีอย่างน้อย 1 กลุ่ม',
    TOO_MANY_GROUPS: en.errors.TOO_MANY_GROUPS,
    TOGETHER_APART_CLASH: en.errors.TOGETHER_APART_CLASH,
    TOGETHER_UNIT_TOO_LARGE: en.errors.TOGETHER_UNIT_TOO_LARGE,
    TOGETHER_NO_ARRANGEMENT: en.errors.TOGETHER_NO_ARRANGEMENT,
    TOGETHER_SEARCH_GAVE_UP:
      'ที่นี่มีตัวอักษรที่ติดกันมากเกินไป ทำให้ยากที่จะวิเคราะห์ได้ ลองใช้ตัวอักษรน้อยลง หรือเพิ่มขนาดกลุ่มให้ใหญ่ขึ้น',
    KEEP_APART_IMPOSSIBLE: en.errors.KEEP_APART_IMPOSSIBLE,
    KEEP_APART_NO_ARRANGEMENT: en.errors.KEEP_APART_NO_ARRANGEMENT,
    KEEP_APART_SEARCH_GAVE_UP:
      'มีกฎการเว้นระยะห่างที่นี่มากเกินไปจนยากที่จะปฏิบัติตาม ลองลบออกบางส่วนดู',
    BOTH_RULES_NO_ARRANGEMENT: en.errors.BOTH_RULES_NO_ARRANGEMENT,
    BOTH_RULES_SEARCH_GAVE_UP:
      'ที่นี่มีตัวอักษรที่ติดกันและแยกกันมากเกินไป จนไม่สามารถจัดการได้ทั้งหมดในครั้งเดียว ลองใช้ตัวอักษรประเภทใดประเภทหนึ่งให้น้อยลง หรือเพิ่มขนาดกลุ่มให้ใหญ่ขึ้น',
    SEX_NEEDS_ALL_SET: en.errors.SEX_NEEDS_ALL_SET,
    SEX_SEPARATE_SPLITS_UNIT: en.errors.SEX_SEPARATE_SPLITS_UNIT,
    SEX_SEPARATE_IMPOSSIBLE: en.errors.SEX_SEPARATE_IMPOSSIBLE,
    SEX_SEPARATE_SEARCH_GAVE_UP:
      'ที่นี่มีตัวอักษรที่ติดกันและแยกกันมากเกินไป ทำให้ยากที่จะจัดการได้พร้อมทั้งต้องแบ่งเด็กชายและเด็กหญิงเป็นกลุ่มต่างกัน ลองใช้ตัวอักษรน้อยลง หรือปิดโหมดนี้ไป',
    PINNED_SPLITS_UNIT: en.errors.PINNED_SPLITS_UNIT,
    PINNED_APART_CLASH: en.errors.PINNED_APART_CLASH,
    PINNED_IN_TWO_GROUPS: en.errors.PINNED_IN_TWO_GROUPS,
    PINNED_TOO_MANY_GROUPS: en.errors.PINNED_TOO_MANY_GROUPS,
  },
  warnings: {
    SEX_SPILLOVER: en.warnings.SEX_SPILLOVER,
    PINNED_MIXED_SEX: en.warnings.PINNED_MIXED_SEX,
    SEX_BOTH_TOO_SMALL: en.warnings.SEX_BOTH_TOO_SMALL,
  },
};
