import type { Catalogue } from './en';

/**
 * vi — generated by `scripts/i18n-scaffold.mjs` from en.ts and the DeepL
 * cache (#22), then REVIEWED BY HAND. Re-rendering discards those reviews, so
 * the generator refuses to overwrite this file without `--force`.
 *
 * Every message is a template rebuilt from DeepL's translation of the
 * sentences it can say, and checked to fill exactly the slots English fills
 * (#136).
 *
 * MACHINE-TRANSLATED COPY IS A FIRST DRAFT. It has been checked for structure
 * — placeholders intact, protected names preserved, nothing empty — and NOT
 * for fluency, which needs a speaker of this language.
 */
export const vi: Catalogue = {
  title: 'Trình tạo nhóm trong lớp học',
  description:
    'Chia lớp học của bạn thành các nhóm ngay lập tức — ngay trên trình duyệt, mà không cần gửi dữ liệu đi đâu cả.',
  heading: 'Trình tạo nhóm trong lớp học',
  lead: 'Hãy cho chương trình biết lớp của bạn có bao nhiêu học sinh và bạn muốn mỗi nhóm có bao nhiêu học sinh. Chương trình sẽ xáo trộn danh sách và phân chia học sinh vào các nhóm, đồng thời đảm bảo không có nhóm nào có số lượng học sinh ít hơn số lượng bạn yêu cầu.',
  privacy:
    'Mọi thứ đều diễn ra ngay trong trình duyệt của bạn. Danh sách lớp học sẽ không bao giờ được chuyển ra khỏi trang này.',
  howToHeading: 'Cách sử dụng',
  howToWhat:
    'Được phát triển dành cho giáo viên, bởi Shyden. Việc chia lớp một cách công bằng tốn thời gian mà bạn không có, và nếu làm thủ công thì dễ dẫn đến tranh cãi về việc thiên vị. Công cụ này giúp bạn hoàn thành việc đó chỉ với một cú nhấp chuột — miễn phí, không cần đăng ký, và mọi thông tin về lớp học của bạn sẽ không bao giờ rời khỏi trình duyệt.',
  howToSteps: [
    'Hãy cho biết trong lớp bạn có bao nhiêu học sinh.',
    'Hãy chọn cách chia chúng ra.',
    'Nhấn vào “Tạo nhóm”.',
  ],
  classLabel: 'Lớp (tùy chọn)',
  studentsLabel: 'Số lượng học sinh',
  studentsHelp:
    'Các học sinh được giấu tên và đánh số — Học sinh 1, Học sinh 2, v.v.',
  studentsLockedReason:
    'Được thiết lập theo danh sách của bạn. Để thay đổi danh sách này, hãy thêm hoặc xóa học sinh trong phần “Chi tiết học sinh”.',
  modeLabel: 'Phân chia theo',
  modePerGroup: 'Số học sinh trong mỗi nhóm',
  modeGroupCount: 'Số lượng nhóm',
  groupSizeLabel: 'Học sinh trong mỗi nhóm',
  groupCountLabel: 'Có bao nhiêu nhóm',
  sexMixLabel: 'Phân chia nam và nữ một cách cân bằng',
  sexSeparateLabel: 'Giữ các bé trai và bé gái riêng biệt',
  sexWhyNoList:
    'Hãy thêm học sinh của bạn vào phần “Thông tin học sinh” và chọn M hoặc F cho từng em để sử dụng các tính năng này.',
  sexWhyUnset:
    '{unset} Trong số các học sinh thuộc nhóm “{grouped}” đang được phân nhóm, có những em chưa được thiết lập giới tính. Hãy mở chi tiết học sinh và thiết lập giới tính là “M” hoặc “F” cho các em để họ có thể sử dụng các tính năng này.',
  sexWhyReturning:
    '{who} đã trở lại nhưng chưa có cài đặt giới tính. Các tùy chọn này cần có cài đặt giới tính cho từng học sinh được phân nhóm.',
  leftoversLabel: 'Nếu vẫn còn học sinh',
  leftoversSpread: 'Chia đều chúng ra',
  leftoversBunch: 'Gộp tất cả vào một nhóm',
  leftoversHelp:
    'Dù thế nào đi nữa, không có nhóm nào có quy mô nhỏ hơn quy mô mà bạn đã chọn.',
  soundOn: 'Bật âm thanh',
  soundOff: 'Hãy lên tiếng',
  speedLabel: 'Tốc độ',
  speedNormal: 'Bình thường',
  speedFast: 'Nhanh',
  speedSkip: 'Bỏ qua phần hoạt hình',
  sectionStudentsHeading: 'Thông tin về học sinh',
  sectionGroupingHeading: 'Các tùy chọn phân nhóm',
  sectionImportExportHeading: 'Nhập khẩu / xuất khẩu',
  sectionSoundHeading: 'Âm thanh và hoạt hình',
  rosterColNumber: '#',
  rosterColName: 'Tên',
  rosterColSex: 'Tình dục',
  rosterColAbsent: 'Vắng mặt',
  rosterColTogether: 'Cùng nhau',
  rosterColApart: 'Tách biệt',
  rosterUnset: '—',
  rosterSexMale: 'M',
  rosterSexFemale: 'F',
  rosterAddStudent: '+ Thêm học sinh',
  rosterAddSeveral: '+ Thêm một vài…',
  rosterHowMany: 'Thêm bao nhiêu?',
  rosterAddConfirm: 'Thêm',
  rosterAbsentPill: 'vắng mặt',
  rosterAbsentConsequence:
    'Học sinh được ghi là vắng mặt sẽ không được tính vào khi chia nhóm.',
  rosterCountLine: '{total} học sinh · {here} có mặt · {absent} vắng mặt',
  rosterDuplicateMessage:
    'Số {number} đã được {name} sử dụng. Mỗi học sinh cần có một số riêng.',
  rosterNoSexMessage:
    '{names} Vẫn cần M hoặc F. Mỗi học sinh phải có một cái trước khi có thể chia nhóm.',
  rosterClashMessage:
    '{names} được giữ lại với nhau, nên không thể tách chúng ra được.',
  rosterGapWarning:
    'Danh sách lớp của bạn có vẻ chưa đầy đủ. Thiếu các học sinh số {missing}. Nếu những em này đã nghỉ học thì không sao cả — hãy mở phần “Thông tin học sinh” để kiểm tra.',
  rosterOpenRefusedMessage:
    'Thông tin học sinh có thể lưu trữ tối đa {max} học sinh. Hãy giảm số lượng này để hiển thị lớp học này dưới dạng danh sách riêng lẻ.',
  rosterAtLimitMessage:
    'Thông tin học sinh có thể lưu trữ tối đa {max} học sinh. Hãy xóa một học sinh để thêm học sinh khác.',
  rosterRoomMessage: '{room} vẫn còn chỗ cho thêm nhiều học sinh nữa.',
  rosterRemove: 'Xóa',
  rosterClearAll: 'Xóa tất cả',
  stateNoneAdded: 'chưa có mục nào được thêm vào',
  stateNamed: '{n} có tên là',
  stateAbsent: '{n} vắng mặt',
  stateTogether: '{n} cùng nhau',
  stateApart: '{n} riêng biệt',
  stateAdded: '{n} đã thêm',
  stateNone: 'không có',
  stateMixed: 'phân loại theo giới tính',
  stateSeparated: 'phân chia theo giới tính',
  stateBunched: 'thức ăn thừa trong một nhóm',
  stateNothingToSave: 'Chưa có gì để lưu cả',
  stateUnsaved: 'các thay đổi chưa được lưu — hãy xuất để giữ lại chúng',
  makeGroups: 'Tạo nhóm',
  again: 'Trộn lại',
  needsJs: 'Công cụ này yêu cầu bật JavaScript.',
  resultsHeading: 'Các nhóm của bạn',
  resultsHeadingNamed: '{className} — các nhóm của bạn',
  resultsSummary:
    '{groups} các nhóm gồm các sinh viên thuộc chương trình “{students}”.',
  groupLabel: 'Nhóm{n}',
  studentNumber: 'Học sinh{n}',
  staleMode: 'Các nhóm này đã lỗi thời — quy mô nhóm đã thay đổi.',
  staleLeftovers:
    'Các nhóm này đã lỗi thời — lựa chọn “thức ăn thừa” đã thay đổi.',
  staleSexMode:
    'Các nhóm này đã lỗi thời — cách phân nhóm các em trai và em gái đã thay đổi.',
  staleRoster: 'Các nhóm này đã lỗi thời — danh sách lớp đã thay đổi.',
  csvProblemEmptyFile: 'Tệp này trống.',
  csvProblemUnreadable: 'Không thể đọc được tệp đó. Hãy thử chọn lại tệp đó.',
  csvProblemNoNumberColumn:
    'Tệp này không có cột số. Mỗi học sinh cần có một cột như vậy.',
  csvProblemNumberBlank:
    'Dòng {row} — ô số để trống. Mỗi học sinh cần có một cái.',
  csvProblemNumberNotWhole:
    "Dòng {row} — số '{value}' không phải là số nguyên.",
  csvProblemDuplicateNumber:
    'Dòng {row} — số {value} đã được sử dụng bởi dòng {firstRow}.',
  csvProblemSex:
    "Dòng {row} — thuộc tính '{value}' không được hiểu. Hãy sử dụng {accepted} hoặc để trống.",
  csvProblemAbsent:
    "Dòng {row} — thiếu '{value}', không thể hiểu được. Vui lòng sử dụng {accepted} hoặc để trống.",
  csvProblemLetter:
    "Dòng {row} — {column} '{value}' không phải là một ký tự duy nhất.",
  csvProblemTooMany:
    'Tệp này chứa {found} học sinh. Thông tin chi tiết về học sinh có thể chứa tối đa {max}.',
  csvWrongLanguage:
    'Đây có vẻ là danh sách các lớp trong thư viện {language}. Hãy mở phiên bản {version} của trang này để nhập nó.',
  csvLanguageName: {
    en: 'Tiếng Anh',
    id: 'Tiếng Indonesia',
    zh: 'Tiếng Trung',
    vi: 'Tiếng Việt',
    th: 'Tiếng Thái',
  },
  csvLanguageVersion: {
    en: 'Tiếng Anh',
    id: 'Tiếng Indonesia',
    zh: 'Tiếng Trung',
    vi: 'Tiếng Việt',
    th: 'Tiếng Thái',
  },
  ioExportClassList: 'Xuất danh sách các lớp học',
  ioExportGroups: 'Nhóm xuất khẩu',
  ioDownloadTemplate: 'Tải xuống mẫu',
  ioImportLabel: 'Nhập danh sách lớp học',
  ioProblemsHeading: 'Tệp này chưa được nhập:',
  ioReplaceWarning:
    'Danh sách này sẽ thay thế danh sách lớp hiện tại của bạn — các học sinh thuộc nhóm “{total}” và “{named}” được liệt kê trong danh sách.',
  ioReplaceConfirm: 'Thay thế nó',
  ioReplaceCancel: 'Giữ lại những gì tôi đang có',
  ioImported: 'Đã nhập danh sách học sinh từ {total}.',
  ioBothLanguages: 'Cũng xuất sang ngôn ngữ khác',
  ioBothLanguagesHint:
    'Tệp của bạn hiện đã được lưu lại bằng ngôn ngữ này. Một tab thứ hai sẽ mở ra bằng ngôn ngữ bạn đã chọn, với danh sách lớp học giống hệt, để bạn kiểm tra và lưu lại tại đó. Không có dữ liệu nào được lưu trữ và cũng không có dữ liệu nào được gửi đi đâu cả.',
  ioHandoverBlocked:
    'Không thể mở tab thứ hai. Danh sách lớp học của bạn vẫn còn ở đây — hãy cho phép cửa sổ bật lên và thử lại.',
  ioHandoverTimedOut:
    'Tab thứ hai chưa bao giờ yêu cầu danh sách lớp. Danh sách lớp của bạn vẫn còn ở đây — hãy đóng tab đó lại và thử lại.',
  ioHandoverNotOffered:
    'Chưa nhận được danh sách lớp. Hãy quay lại tab khác và thử lại.',
  ioHandoverSent:
    'Danh sách lớp của bạn hiện đã được mở trên trang {language}.',
  printOpen: 'In',
  printHeading: 'In',
  printWhat: 'In những gì',
  printWhatClassList: 'Danh sách lớp',
  printWhatGroups: 'Kết quả của nhóm',
  printWhatBoth: 'Cả hai',
  printOnTheClassList: 'Trong danh sách lớp',
  printShowAbsent: 'Hiển thị danh sách học sinh vắng mặt',
  printShowLetters:
    'Hiển thị các ký tự biểu thị giới tính và trạng thái "cùng nhau"/"riêng rẽ"',
  printIncludeAvatars: 'Thêm ảnh đại diện',
  printCancel: 'Hủy',
  printConfirm: 'In',
  printClassListHeading: 'Danh sách lớp',
  printGroupsHeading: 'Các nhóm',
  printedOn: 'Được đăng tải tại {on}',
  printHereToday: '{here} học sinh có mặt hôm nay · {absent} vắng mặt',
  boardOpen: 'Toàn màn hình',
  boardExit: 'Thoát chế độ toàn màn hình',
  boardShuffle: 'Trộn lại',
  staleRefuseExport:
    'Các nhóm này đã lỗi thời. Hãy trộn lại trước khi lưu chúng.',
  staleRefusePrint:
    'Các nhóm này đã lỗi thời. Hãy xáo trộn lại trước khi in chúng.',
  staleRefuseBoard:
    'Các nhóm này đã lỗi thời. Hãy trộn lại trước khi hiển thị chúng.',
  errors: {
    NO_STUDENTS:
      'Thêm một số học sinh vào, hoặc đảm bảo rằng ít nhất một trong số các em đó không bị ghi là vắng mặt.',
    TOO_MANY_STUDENTS:
      'Số lượng học sinh đó vượt quá giới hạn mà công cụ này cho phép. Số lượng tối đa là {max}.',
    DUPLICATE_NUMBER:
      'Số học sinh {number} được sử dụng hai lần. Hãy cấp cho mỗi học sinh một số riêng.',
    INVALID_GROUP_SIZE: 'Mỗi nhóm cần có ít nhất 1 học sinh.',
    INVALID_GROUP_COUNT: 'Bạn cần có ít nhất 1 nhóm.',
    TOO_MANY_GROUPS:
      'Số lượng sinh viên không đủ để chia thành nhiều nhóm như vậy. Số lượng tối đa mà bạn có thể chia thành là {max}.',
    TOGETHER_APART_CLASH:
      '{names} được đánh dấu để vừa ở bên nhau vừa phải tách xa nhau cùng một lúc. Hãy loại bỏ chữ cái “cùng nhau” hoặc chữ cái “tách xa” khỏi một trong hai từ đó.',
    TOGETHER_UNIT_TOO_LARGE:
      'Chữ cái “{letter}” có {unit} học sinh, nhưng nhóm lớn nhất ở đây chỉ có {groupSize}. Hãy tăng số lượng các nhóm lên, hoặc phân chữ cái “{letter}” cho ít học sinh hơn.',
    TOGETHER_NO_ARRANGEMENT:
      'Không có cách nào để chia lớp của bạn thành các nhóm theo chữ cái ({groupsTried}) mà vẫn giữ được những học sinh cần ở cùng nhau. Hãy tăng quy mô các nhóm lên, hoặc phân bổ mỗi chữ cái cho ít học sinh hơn.',
    TOGETHER_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái ghép lại với nhau nên khó xử lý. Hãy thử dùng ít chữ cái hơn, hoặc gộp các nhóm lại thành nhóm lớn hơn.',
    KEEP_APART_IMPOSSIBLE:
      '{names} Tất cả đều cần được tách biệt với nhau, vì vậy bạn sẽ cần ít nhấ{groupsNeeded}nhóm. Hãy tạo thêm nhóm hoặc loại bỏ một trong các quy tắc.',
    KEEP_APART_NO_ARRANGEMENT:
      'Không có cách nào để chia lớp của bạn thành các nhóm “{groupsTried}” mà vẫn đảm bảo giữ khoảng cách cho những người cần phải cách ly. Hoặc là tạo thêm nhóm, hoặc là bỏ bớt một trong các quy tắc.',
    KEEP_APART_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều quy tắc ngăn cách, khó mà xử lý hết được. Hãy thử loại bỏ một số quy tắc trong số đó.',
    BOTH_RULES_NO_ARRANGEMENT:
      'Không có cách nào để chia lớp của bạn thành các nhóm theo quy tắc “{groupsTried}” mà vẫn đáp ứng được đồng thời tất cả các quy tắc “cùng chữ cái” và “riêng chữ cái”. Quá trình tìm kiếm không thể xác định được quy tắc nào là nguyên nhân gây ra vấn đề, vì vậy hãy thử một trong hai giải pháp sau: tăng kích thước các nhóm hoặc chỉ áp dụng quy tắc “cùng chữ cái” cho ít học sinh hơn, hoặc chia thành nhiều nhóm hơn, hoặc loại bỏ một trong các quy tắc “riêng chữ cái”.',
    BOTH_RULES_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái ghép và chữ cái tách để có thể xử lý hết cùng một lúc. Hãy thử sử dụng ít chữ cái hơn cho cả hai loại, hoặc chia thành các nhóm lớn hơn.',
    SEX_NEEDS_ALL_SET:
      '{names} Chưa thiết lập giới tính, do đó chế độ này sẽ không hoạt động cho đến khi tất cả học sinh đều được thiết lập. Hãy thiết lập giới tính cho từng em hoặc tắt tính năng này đi.',
    SEX_SEPARATE_SPLITS_UNIT:
      '{names} được đánh dấu là ở cùng nhau, nhưng không phải tất cả đều cùng giới tính, nên chúng không thể tạo thành một nhóm cùng giới. Hãy gỡ bỏ chữ “cùng” khỏi một trong số chúng, hoặc tắt chế độ này đi.',
    SEX_SEPARATE_IMPOSSIBLE:
      'Không thể chia các em trai và em gái thành các nhóm riêng biệt trong các nhóm “{groupsRequested}” mà vẫn đảm bảo tuân thủ các quy tắc khác của bạn. Chức năng tìm kiếm không thể xác định quy tắc nào là nguyên nhân gây ra vấn đề, vì vậy hãy thử một trong hai cách khắc phục sau: yêu cầu số lượng nhóm khác hoặc tắt chế độ này.',
    SEX_SEPARATE_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái ghép và tách rời, khiến việc xử lý chúng trở nên khó khăn trong khi vẫn phải giữ các nhóm nam và nữ riêng biệt. Hãy thử sử dụng ít chữ cái hơn hoặc tắt chế độ này đi.',
    PINNED_SPLITS_UNIT:
      '{names} được đánh dấu để ở cùng nhau, nhưng chỉ một số trong số đó nằm trong nhóm đã được ghim. Hãy bỏ ghim nhóm đó, hoặc gỡ bỏ chữ “cùng nhau” khỏi những người nằm ngoài nhóm.',
    PINNED_APART_CLASH:
      '{names} được đánh dấu để tách biệt với nhau, nhưng khi ghim nhóm lại, chúng sẽ nằm chung trong cùng một nhóm. Hãy bỏ ghim nhóm đó, hoặc xóa ký hiệu “tách biệt” khỏi một trong số chúng.',
    PINNED_IN_TWO_GROUPS:
      '{name} đang được gắn vào hai nhóm khác nhau cùng một lúc. Một học sinh chỉ có thể được gắn vào một nhóm duy nhất. Hãy gỡ học sinh đó ra khỏi một trong hai nhóm.',
    PINNED_TOO_MANY_GROUPS:
      '{situation, select, over {Các nhóm của bạn hiện đã sử dụng các nhóm {pinnedGroupCount} — nhiều hơn số nhóm {requestedGroups} mà bạn đã yêu cầu — khiến các học sinh tại {remainingStudents} không còn nhóm nào dành cho họ. Hãy hủy ghim một nhóm hoặc yêu cầu thêm nhóm.} full {Các nhóm mà bạn đã chọn đã chiếm hết {pinnedGroupCount} trong số các nhóm {requestedGroups} mà bạn yêu cầu, do đó chỉ còn lại {remainingStudents} sinh viên chưa có nhóm nào dành cho họ. Hãy hủy chọn một nhóm hoặc yêu cầu thêm nhóm.} other {Các nhóm mà bạn đã chọn đã chiếm {pinnedGroupCount} trong tổng số {requestedGroups} nhóm mà bạn yêu cầu, do đó chỉ còn lại {remainingStudents} sinh viên — con số này chưa đủ để thành lập các nhóm {poolGroupsNeeded} còn thiếu. Hãy hủy chọn một nhóm hoặc yêu cầu ít nhóm hơn.}}',
  },
  warnings: {
    SEX_SPILLOVER:
      '{sex, select, M {{names} đã gia nhập một nhóm các bạn nữ vì không có đủ bạn nam để thành lập một nhóm riêng. Đó chỉ đơn giản là cách phân chia số lượng, chứ không phải là một sai lầm cần khắc phục.} other {{names} đã gia nhập một nhóm các cậu bé vì không có đủ các bạn nữ để thành lập một nhóm riêng. Đó chỉ đơn giản là cách phân chia số lượng, chứ không phải là một sai lầm cần khắc phục.}}',
    PINNED_MIXED_SEX:
      '{names} được ghim lại thành một nhóm, nhưng không phải tất cả đều cùng giới tính, nên nhóm này không được chia theo giới tính như các nhóm khác. Đó chính là yêu cầu trong bài đăng, chứ không phải là một sai sót cần sửa.',
    SEX_BOTH_TOO_SMALL:
      '{names} đã được xếp vào một nhóm chung vì số lượng của cả hai giới đều không đủ để lập thành một nhóm riêng. Đó chỉ đơn giản là cách phân chia số lượng, chứ không phải là một sai sót cần khắc phục.',
  },
};
