import { en, type Strings } from './en';

/**
 * vi — generated by `scripts/i18n-scaffold.mjs` from en.ts and the DeepL
 * cache (#22), then REVIEWED BY HAND. Re-rendering discards those reviews, so
 * the generator refuses to overwrite this file without `--force`.
 *
 * 51 keys are the English original, referenced as `en.<key>` rather
 * than copied: every parameterised message in this catalogue is an arrow
 * function, and a translator returns prose, not a function body. They are
 * visible here, greppable, and pinned as an exact set by
 * tests/unit/locale-fallbacks.test.ts — so one cannot be added quietly, and
 * one that gets translated must be removed from that list to stay green.
 *
 * MACHINE-TRANSLATED COPY IS A FIRST DRAFT. It has been checked for structure
 * — placeholders intact, protected names preserved, nothing empty — and NOT
 * for fluency, which needs a speaker of this language.
 */
export const vi: Strings = {
  title: 'Trình tạo nhóm trong lớp học',
  description:
    'Chia lớp học của bạn thành các nhóm ngay lập tức — ngay trên trình duyệt, mà không cần gửi dữ liệu đi đâu cả.',
  heading: 'Trình tạo nhóm trong lớp học',
  lead: 'Hãy cho chương trình biết lớp của bạn có bao nhiêu học sinh và bạn muốn mỗi nhóm có bao nhiêu học sinh. Chương trình sẽ xáo trộn danh sách và phân chia học sinh vào các nhóm, đồng thời đảm bảo không có nhóm nào có số lượng học sinh ít hơn số lượng bạn yêu cầu.',
  privacy:
    'Mọi thứ đều diễn ra ngay trong trình duyệt của bạn. Danh sách lớp học sẽ không bao giờ được chuyển ra khỏi trang này.',
  howToHeading: 'Cách sử dụng',
  howToWhat:
    'Được phát triển dành cho giáo viên, bởi Shyden. Việc chia lớp một cách công bằng tốn thời gian mà bạn không có, và nếu làm thủ công thì dễ dẫn đến tranh cãi về việc thiên vị. Công cụ này giúp bạn hoàn thành việc đó chỉ với một cú nhấp chuột — miễn phí, không cần đăng ký, và mọi thông tin về lớp học của bạn sẽ không bao giờ rời khỏi trình duyệt.',
  howToSteps: [
    'Hãy cho biết trong lớp bạn có bao nhiêu học sinh.',
    'Hãy chọn cách chia chúng ra.',
    'Nhấn vào “Tạo nhóm”.',
  ],
  classLabel: 'Lớp (tùy chọn)',
  studentsLabel: 'Số lượng học sinh',
  studentsHelp:
    'Các học sinh được giấu tên và đánh số — Học sinh 1, Học sinh 2, v.v.',
  studentsLockedReason:
    'Được thiết lập theo danh sách của bạn. Để thay đổi danh sách này, hãy thêm hoặc xóa học sinh trong phần “Chi tiết học sinh”.',
  modeLabel: 'Phân chia theo',
  modePerGroup: 'Số học sinh trong mỗi nhóm',
  modeGroupCount: 'Số lượng nhóm',
  groupSizeLabel: 'Học sinh trong mỗi nhóm',
  groupCountLabel: 'Có bao nhiêu nhóm',
  sexMixLabel: 'Phân chia nam và nữ một cách cân bằng',
  sexSeparateLabel: 'Giữ các bé trai và bé gái riêng biệt',
  sexWhyNoList:
    'Hãy thêm học sinh của bạn vào phần “Thông tin học sinh” và chọn M hoặc F cho từng em để sử dụng các tính năng này.',
  sexWhyUnset: en.sexWhyUnset,
  sexWhyReturning: en.sexWhyReturning,
  leftoversLabel: 'Nếu vẫn còn học sinh',
  leftoversSpread: 'Chia đều chúng ra',
  leftoversBunch: 'Gộp tất cả vào một nhóm',
  leftoversHelp:
    'Dù thế nào đi nữa, không có nhóm nào có quy mô nhỏ hơn quy mô mà bạn đã chọn.',
  soundOn: 'Bật âm thanh',
  soundOff: 'Hãy lên tiếng',
  speedLabel: 'Tốc độ',
  speedNormal: 'Bình thường',
  speedFast: 'Nhanh',
  speedSkip: 'Bỏ qua phần hoạt hình',
  sectionStudentsHeading: 'Thông tin về học sinh',
  sectionGroupingHeading: 'Các tùy chọn phân nhóm',
  sectionImportExportHeading: 'Nhập khẩu / xuất khẩu',
  sectionSoundHeading: 'Âm thanh và hoạt hình',
  rosterColNumber: '#',
  rosterColName: 'Tên',
  rosterColSex: 'Tình dục',
  rosterColAbsent: 'Vắng mặt',
  rosterColTogether: 'Cùng nhau',
  rosterColApart: 'Tách biệt',
  rosterUnset: '—',
  rosterSexMale: 'M',
  rosterSexFemale: 'F',
  rosterAddStudent: '+ Thêm học sinh',
  rosterAddSeveral: '+ Thêm một vài…',
  rosterHowMany: 'Thêm bao nhiêu?',
  rosterAddConfirm: 'Thêm',
  rosterAbsentPill: 'vắng mặt',
  rosterAbsentConsequence:
    'Học sinh được ghi là vắng mặt sẽ không được tính vào khi chia nhóm.',
  rosterCountLine: en.rosterCountLine,
  rosterDuplicateMessage: en.rosterDuplicateMessage,
  rosterNoSexMessage: en.rosterNoSexMessage,
  rosterClashMessage: en.rosterClashMessage,
  rosterGapWarning: en.rosterGapWarning,
  rosterOpenRefusedMessage: en.rosterOpenRefusedMessage,
  rosterAtLimitMessage: en.rosterAtLimitMessage,
  rosterRoomMessage: en.rosterRoomMessage,
  rosterRemove: 'Xóa',
  rosterClearAll: 'Xóa tất cả',
  stateNoneAdded: 'chưa có mục nào được thêm vào',
  stateNamed: en.stateNamed,
  stateAbsent: en.stateAbsent,
  stateTogether: en.stateTogether,
  stateApart: en.stateApart,
  stateAdded: en.stateAdded,
  stateNone: 'không có',
  stateMixed: 'phân loại theo giới tính',
  stateSeparated: 'phân chia theo giới tính',
  stateBunched: 'thức ăn thừa trong một nhóm',
  stateNothingToSave: 'Chưa có gì để lưu cả',
  stateUnsaved: 'các thay đổi chưa được lưu — hãy xuất để giữ lại chúng',
  makeGroups: 'Tạo nhóm',
  again: 'Trộn lại',
  needsJs: 'Công cụ này yêu cầu bật JavaScript.',
  resultsHeading: 'Các nhóm của bạn',
  resultsHeadingNamed: en.resultsHeadingNamed,
  resultsSummary: en.resultsSummary,
  groupLabel: en.groupLabel,
  studentNumber: en.studentNumber,
  staleMode: 'Các nhóm này đã lỗi thời — quy mô nhóm đã thay đổi.',
  staleLeftovers:
    'Các nhóm này đã lỗi thời — lựa chọn “thức ăn thừa” đã thay đổi.',
  staleSexMode:
    'Các nhóm này đã lỗi thời — cách phân nhóm các em trai và em gái đã thay đổi.',
  staleRoster: 'Các nhóm này đã lỗi thời — danh sách lớp đã thay đổi.',
  csvProblemEmptyFile: 'Tệp này trống.',
  csvProblemUnreadable: 'Không thể đọc được tệp đó. Hãy thử chọn lại tệp đó.',
  csvProblemNoNumberColumn:
    'Tệp này không có cột số. Mỗi học sinh cần có một cột như vậy.',
  csvProblemNumberBlank: en.csvProblemNumberBlank,
  csvProblemNumberNotWhole: en.csvProblemNumberNotWhole,
  csvProblemDuplicateNumber: en.csvProblemDuplicateNumber,
  csvProblemSex: en.csvProblemSex,
  csvProblemAbsent: en.csvProblemAbsent,
  csvProblemLetter: en.csvProblemLetter,
  csvProblemTooMany: en.csvProblemTooMany,
  csvWrongLanguage: en.csvWrongLanguage,
  csvLanguageName: {
    en: 'Tiếng Anh',
    id: 'Tiếng Indonesia',
    zh: 'Tiếng Trung',
    vi: 'Tiếng Việt',
    th: 'Tiếng Thái',
  },
  csvLanguageVersion: {
    en: 'Tiếng Anh',
    id: 'Tiếng Indonesia',
    zh: 'Tiếng Trung',
    vi: 'Tiếng Việt',
    th: 'Tiếng Thái',
  },
  ioExportClassList: 'Xuất danh sách các lớp học',
  ioExportGroups: 'Nhóm xuất khẩu',
  ioDownloadTemplate: 'Tải xuống mẫu',
  ioImportLabel: 'Nhập danh sách lớp học',
  ioProblemsHeading: 'Tệp này chưa được nhập:',
  ioReplaceWarning: en.ioReplaceWarning,
  ioReplaceConfirm: 'Thay thế nó',
  ioReplaceCancel: 'Giữ lại những gì tôi đang có',
  ioImported: en.ioImported,
  ioBothLanguages: 'Cũng xuất sang ngôn ngữ khác',
  ioBothLanguagesHint:
    'Tệp của bạn hiện đã được lưu lại bằng ngôn ngữ này. Một tab thứ hai sẽ mở ra bằng ngôn ngữ bạn đã chọn, với danh sách lớp học giống hệt, để bạn kiểm tra và lưu lại tại đó. Không có dữ liệu nào được lưu trữ và cũng không có dữ liệu nào được gửi đi đâu cả.',
  ioHandoverBlocked:
    'Không thể mở tab thứ hai. Danh sách lớp học của bạn vẫn còn ở đây — hãy cho phép cửa sổ bật lên và thử lại.',
  ioHandoverTimedOut:
    'Tab thứ hai chưa bao giờ yêu cầu danh sách lớp. Danh sách lớp của bạn vẫn còn ở đây — hãy đóng tab đó lại và thử lại.',
  ioHandoverNotOffered:
    'Chưa nhận được danh sách lớp. Hãy quay lại tab khác và thử lại.',
  ioHandoverSent: en.ioHandoverSent,
  printOpen: 'In',
  printHeading: 'In',
  printWhat: 'In những gì',
  printWhatClassList: 'Danh sách lớp',
  printWhatGroups: 'Kết quả của nhóm',
  printWhatBoth: 'Cả hai',
  printOnTheClassList: 'Trong danh sách lớp',
  printShowAbsent: 'Hiển thị danh sách học sinh vắng mặt',
  printShowLetters:
    'Hiển thị các ký tự biểu thị giới tính và trạng thái "cùng nhau"/"riêng rẽ"',
  printIncludeAvatars: 'Thêm ảnh đại diện',
  printCancel: 'Hủy',
  printConfirm: 'In',
  printClassListHeading: 'Danh sách lớp',
  printGroupsHeading: 'Các nhóm',
  printedOn: en.printedOn,
  printHereToday: en.printHereToday,
  boardOpen: 'Toàn màn hình',
  boardExit: 'Thoát chế độ toàn màn hình',
  boardShuffle: 'Trộn lại',
  staleRefuseExport:
    'Các nhóm này đã lỗi thời. Hãy trộn lại trước khi lưu chúng.',
  staleRefusePrint:
    'Các nhóm này đã lỗi thời. Hãy xáo trộn lại trước khi in chúng.',
  staleRefuseBoard:
    'Các nhóm này đã lỗi thời. Hãy trộn lại trước khi hiển thị chúng.',
  errors: {
    NO_STUDENTS:
      'Thêm một số học sinh vào, hoặc đảm bảo rằng ít nhất một trong số các em đó không bị ghi là vắng mặt.',
    TOO_MANY_STUDENTS: en.errors.TOO_MANY_STUDENTS,
    DUPLICATE_NUMBER: en.errors.DUPLICATE_NUMBER,
    INVALID_GROUP_SIZE: 'Mỗi nhóm cần có ít nhất 1 học sinh.',
    INVALID_GROUP_COUNT: 'Bạn cần có ít nhất 1 nhóm.',
    TOO_MANY_GROUPS: en.errors.TOO_MANY_GROUPS,
    TOGETHER_APART_CLASH: en.errors.TOGETHER_APART_CLASH,
    TOGETHER_UNIT_TOO_LARGE: en.errors.TOGETHER_UNIT_TOO_LARGE,
    TOGETHER_NO_ARRANGEMENT: en.errors.TOGETHER_NO_ARRANGEMENT,
    TOGETHER_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái ghép lại với nhau nên khó xử lý. Hãy thử dùng ít chữ cái hơn, hoặc gộp các nhóm lại thành nhóm lớn hơn.',
    KEEP_APART_IMPOSSIBLE: en.errors.KEEP_APART_IMPOSSIBLE,
    KEEP_APART_NO_ARRANGEMENT: en.errors.KEEP_APART_NO_ARRANGEMENT,
    KEEP_APART_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều quy tắc ngăn cách, khó mà xử lý hết được. Hãy thử loại bỏ một số quy tắc trong số đó.',
    BOTH_RULES_NO_ARRANGEMENT: en.errors.BOTH_RULES_NO_ARRANGEMENT,
    BOTH_RULES_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái ghép và chữ cái tách để có thể xử lý hết cùng một lúc. Hãy thử sử dụng ít chữ cái hơn cho cả hai loại, hoặc chia thành các nhóm lớn hơn.',
    SEX_NEEDS_ALL_SET: en.errors.SEX_NEEDS_ALL_SET,
    SEX_SEPARATE_SPLITS_UNIT: en.errors.SEX_SEPARATE_SPLITS_UNIT,
    SEX_SEPARATE_IMPOSSIBLE: en.errors.SEX_SEPARATE_IMPOSSIBLE,
    SEX_SEPARATE_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái ghép và tách rời, khiến việc xử lý chúng trở nên khó khăn trong khi vẫn phải giữ các nhóm nam và nữ riêng biệt. Hãy thử sử dụng ít chữ cái hơn hoặc tắt chế độ này đi.',
    PINNED_SPLITS_UNIT: en.errors.PINNED_SPLITS_UNIT,
    PINNED_APART_CLASH: en.errors.PINNED_APART_CLASH,
    PINNED_IN_TWO_GROUPS: en.errors.PINNED_IN_TWO_GROUPS,
    PINNED_TOO_MANY_GROUPS: en.errors.PINNED_TOO_MANY_GROUPS,
  },
  warnings: {
    SEX_SPILLOVER: en.warnings.SEX_SPILLOVER,
    PINNED_MIXED_SEX: en.warnings.PINNED_MIXED_SEX,
    SEX_BOTH_TOO_SMALL: en.warnings.SEX_BOTH_TOO_SMALL,
  },
};
